name: Reusable Workflow Tests - Python 3.7
run-name: Reusable workflow for tests on Python 3.7
on:
  workflow_call:


jobs:
  test-37:
    # Only run tests when NOT pushing tags. Assumes tests already passed from pushed commit that tag is based on.
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python-version:
          - "3.7"
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv tox tox-gh-actions
          pipenv run pip install -r ./.github/dependency_versions/3.7/requirements.txt

      - name: Display installed dependencies
        run: |
          echo "Pipenv installed Django version:"
          pipenv run django-admin --version
          echo ""
          echo "Installed dependencies are:"
          pipenv run pip list

      - name: Test with tox
        run: pipenv run tox

      - name: Rename coverage results
        run: |
          ls -la .coverage
          mv .coverage .coverage.${{ matrix.python-version }}
          ls -la .coverage.${{ matrix.python-version }}

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: .coverage.${{ matrix.python-version }}
          overwrite: true
          include-hidden-files: true
